import { useCallback, useEffect, useState } from "react";
import { StickyNote, Pin, Trash2, Loader2 } from "lucide-react";
import { adminApi } from "../../lib/api";
import { useAuth } from "../../context/AuthContext";

// The notes an admin leaves for the next admin, on a traveller or a trip.
//
// The activity log answers "what was done to this record". This answers "what
// do we already know about it" — the phone call, the refund promised, the
// itinerary regenerated by hand — which otherwise lives in one person's
// memory and is lost the moment somebody else picks up the question.
//
// Pinned notes sort first, so the standing fact about an account doesn't fall
// off the end of a list of day-to-day remarks.
const when = (d) =>
  new Date(d).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" });

export default function AdminNotes({ targetType, targetId }) {
  const { user } = useAuth();
  const [notes, setNotes] = useState([]);
  const [draft, setDraft] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [busyId, setBusyId] = useState(null);
  const [error, setError] = useState("");

  const load = useCallback(() => {
    if (!targetId) return;
    setLoading(true);
    adminApi.notes
      .list(targetType, targetId)
      .then((res) => setNotes(res.notes || []))
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }, [targetType, targetId]);

  useEffect(load, [load]);

  async function add(event) {
    event.preventDefault();
    if (!draft.trim()) return;
    setSaving(true);
    setError("");
    try {
      await adminApi.notes.create({ target_type: targetType, target_id: targetId, body: draft.trim() });
      setDraft("");
      load();
    } catch (err) {
      setError(err.message);
    } finally {
      setSaving(false);
    }
  }

  async function act(id, fn) {
    setBusyId(id);
    setError("");
    try {
      await fn();
      load();
    } catch (err) {
      setError(err.message);
    } finally {
      setBusyId(null);
    }
  }

  // The server enforces this too; here it only decides whether to draw the
  // buttons at all.
  const mine = (note) => note.author_id === user?.id || user?.role === "owner";

  return (
    <section className="mb-6">
      <div className="flex items-center gap-2 mb-3">
        <StickyNote className="w-4 h-4 text-ink-900/40" />
        <h4 className="font-display text-base text-ink-900">Notes</h4>
        <span className="text-xs text-ink-900/40">{notes.length}</span>
      </div>

      {error && <p className="text-xs text-sunset-dark mb-2">{error}</p>}

      <form onSubmit={add} className="mb-3">
        <textarea
          rows={2}
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          maxLength={2000}
          placeholder="What should the next admin to open this know?"
          className="input resize-y"
        />
        <div className="flex justify-end mt-2">
          <button type="submit" disabled={saving || !draft.trim()} className="btn-secondary text-xs">
            {saving ? "Saving…" : "Add note"}
          </button>
        </div>
      </form>

      {loading ? (
        <p className="flex items-center gap-2 text-xs text-ink-900/45">
          <Loader2 className="w-3.5 h-3.5 animate-spin" /> Loading notes…
        </p>
      ) : notes.length === 0 ? (
        <p className="text-xs text-ink-900/40">No notes yet.</p>
      ) : (
        <ul className="space-y-2">
          {notes.map((note) => (
            <li
              key={note._id}
              className={`text-sm rounded-xl px-3 py-2.5 border ${
                note.pinned ? "bg-gold/10 border-gold/40" : "bg-surface border-sand"
              } ${busyId === note._id ? "opacity-50" : ""}`}
            >
              <p className="text-ink-900/80 whitespace-pre-wrap break-words">{note.body}</p>
              <div className="flex items-center gap-2 mt-1.5 text-2xs text-ink-900/45">
                <span>{note.author_name || note.author_email}</span>
                <span>·</span>
                <span>{when(note.created_at)}</span>
                {mine(note) && (
                  <span className="ml-auto flex items-center gap-2">
                    <button
                      type="button"
                      title={note.pinned ? "Unpin" : "Pin to the top"}
                      onClick={() => act(note._id, () => adminApi.notes.update(note._id, { pinned: !note.pinned }))}
                      className={note.pinned ? "text-gold" : "text-ink-900/35 hover:text-ink-900"}
                    >
                      <Pin className="w-3.5 h-3.5" />
                    </button>
                    <button
                      type="button"
                      title="Delete note"
                      onClick={() => act(note._id, () => adminApi.notes.remove(note._id))}
                      className="text-ink-900/35 hover:text-sunset-dark"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </span>
                )}
              </div>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}
