// npm run images:upload            — report what would happen, change nothing
// npm run images:upload -- --apply — upload, write the URLs, rewrite the map
//
// Puts real photographs behind the destination, attraction and hotel cards.
// Everything else in this app answers from the database; images are the one
// thing a database can't seed itself, so this is the manual step that fills
// them in.
//
// Dry run by default because MONGODB_URI points at the shared cluster holding
// the seeded demo data, and because an upload costs Cloudinary quota. Running
// it with no flags tells you exactly which files match a catalogue slug and
// which don't, without touching either.
import "dotenv/config";
import fs from "node:fs/promises";
import path from "node:path";
import mongoose from "mongoose";
import { connectDB } from "../config/db.js";
import Destination from "../models/Destination.js";
import Attraction from "../models/Attraction.js";
import Hotel from "../models/Hotel.js";
import { isConfigured, uploadPlaceImage } from "../services/cloudinaryImages.js";
import { destinationImages, attractionImages, hotelImages } from "../seed/data/placeImages.js";

const args = process.argv.slice(2);
const apply = args.includes("--apply");
const dirArg = args.find((a) => a.startsWith("--dir="));
const ROOT = path.resolve(process.cwd(), dirArg ? dirArg.slice("--dir=".length) : "place-images");

const EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".webp", ".avif"]);

// One entry per collection: where its files live, which model to write, which
// field holds the URL, and which exported map it lands in.
const KINDS = [
  { dir: "destinations", model: Destination, field: "hero_image", existing: destinationImages, export: "destinationImages" },
  { dir: "attractions", model: Attraction, field: "image_url", existing: attractionImages, export: "attractionImages" },
  { dir: "hotels", model: Hotel, field: "image_url", existing: hotelImages, export: "hotelImages" },
];

const MAP_HEADER = `// Slug → hosted image URL, for the three collections that show a place on a
// card: destinations, attractions and hotels.
//
// Generated by \`npm run images:upload\`, and checked in on purpose. The seeder
// replaces those three collections wholesale, so a URL written straight onto
// a document is gone at the next \`npm run seed\` — this file is what makes an
// uploaded image survive a reseed, the same way anything else permanent lives
// under src/seed/data/.
//
// A slug with no entry is not a bug: the client renders its gradient
// fallback, which is what the whole catalogue looks like with Cloudinary
// unconfigured.
`;

async function filesIn(dir) {
  try {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    return entries
      .filter((e) => e.isFile() && EXTENSIONS.has(path.extname(e.name).toLowerCase()))
      .map((e) => e.name);
  } catch (err) {
    if (err.code === "ENOENT") return null;
    throw err;
  }
}

function renderMap(name, entries) {
  const keys = Object.keys(entries).sort();
  if (!keys.length) return `export const ${name} = {};\n`;
  const body = keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(entries[k])},`).join("\n");
  return `export const ${name} = {\n${body}\n};\n`;
}

await connectDB();

let uploaded = 0;
let skipped = 0;
let unmatched = 0;
const results = new Map(KINDS.map((k) => [k.export, { ...k.existing }]));

for (const kind of KINDS) {
  const dir = path.join(ROOT, kind.dir);
  const files = await filesIn(dir);
  if (files === null) {
    console.log(`· ${kind.dir}/ — no such folder, skipped`);
    continue;
  }
  if (!files.length) {
    console.log(`· ${kind.dir}/ — empty`);
    continue;
  }

  // Resolved against the catalogue rather than trusted: a filename typo would
  // otherwise upload an image nothing ever reads, and quietly.
  const slugs = new Set(
    (await kind.model.find({ slug: { $ne: null } }).select("slug").lean()).map((d) => d.slug)
  );

  for (const file of files) {
    const slug = path.basename(file, path.extname(file)).toLowerCase();
    if (!slugs.has(slug)) {
      console.log(`  ✗ ${kind.dir}/${file} — no ${kind.dir.replace(/s$/, "")} has the slug "${slug}"`);
      unmatched += 1;
      continue;
    }

    if (!apply) {
      console.log(`  → ${kind.dir}/${file} → ${slug}.${kind.field}`);
      skipped += 1;
      continue;
    }

    const buffer = await fs.readFile(path.join(dir, file));
    const url = await uploadPlaceImage(buffer, {
      publicId: slug,
      folder: `tourgenie/${kind.dir}`,
      filename: file,
    });
    await kind.model.updateOne({ slug }, { $set: { [kind.field]: url } });
    results.get(kind.export)[slug] = url;
    console.log(`  ✓ ${slug} → ${url}`);
    uploaded += 1;
  }
}

if (apply) {
  const body = [
    MAP_HEADER,
    renderMap("destinationImages", results.get("destinationImages")),
    renderMap("attractionImages", results.get("attractionImages")),
    renderMap("hotelImages", results.get("hotelImages")),
    "export default { destinationImages, attractionImages, hotelImages };\n",
  ].join("\n");
  const target = new URL("../seed/data/placeImages.js", import.meta.url);
  await fs.writeFile(target, body, "utf8");
  console.log(`\n${uploaded} uploaded, ${unmatched} unmatched. src/seed/data/placeImages.js rewritten.`);
} else {
  console.log(
    `\nDry run: ${skipped} file(s) would be uploaded, ${unmatched} unmatched.` +
      (isConfigured() ? "" : "\nCloudinary is not configured — set CLOUDINARY_* in .env before --apply.") +
      "\nRe-run with --apply to upload."
  );
}

await mongoose.disconnect();
