// Support context pinned to a traveller or a trip.
//
// `AuditLog` records what an admin *did*; nothing recorded what they *knew*.
// "Called them on 3 September, refund promised" and "this trip's itinerary
// was regenerated by hand after the AI timed out" have nowhere to live, so
// they end up in someone's memory or a chat thread and the next admin to open
// the record starts from nothing.
//
// Deliberately not an audit entry: notes are editable and deletable, and the
// audit trail must be neither.
import mongoose from "mongoose";
import { TIMESTAMPS } from "./_shared.js";

const adminNoteSchema = new mongoose.Schema(
  {
    target_type: { type: String, enum: ["user", "trip"], required: true },
    target_id: { type: mongoose.Schema.Types.ObjectId, required: true },
    // Kept as text so a note still reads sensibly in a listing after the
    // thing it describes is gone, the same reason AuditLog keeps one.
    target_label: { type: String, default: "" },

    body: { type: String, required: true, trim: true, maxlength: 2000 },
    // Pinned notes sort first: the standing fact about an account ("verified
    // by phone, do not ask again") should not fall off the end of a list of
    // day-to-day remarks.
    pinned: { type: Boolean, default: false },

    author_id: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    author_email: { type: String, default: "" },
    author_name: { type: String, default: "" },
  },
  TIMESTAMPS
);

// The only read there is: every note on one record, newest first.
adminNoteSchema.index({ target_type: 1, target_id: 1, pinned: -1, created_at: -1 });

export default mongoose.model("AdminNote", adminNoteSchema);
